[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["Veronika Vlasova <v.vlasova.dev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
flake8 = "^7.1.1"
gunicorn = "^23.0.0"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
